---
- name: Install postgres packages
  apt:
    name:
      - postgresql
      - python-psycopg2
    state: present
  register: apt_result
  until: apt_result is succeeded
  retries: 3
  environment:
    RUNLEVEL: 1

- name: Make sure postgresql server is started
  service:
    name: postgresql@9.6-main
    enabled: true
    state: started

- name: Install required Python pgsql module for Ansible to manage databases
  apt:
    name: python-psycopg2
    state: present

- name: Wait for postgresql to be ready
  command: /usr/bin/pg_isready
  register: pgready
  until: pgready.rc == 0
  retries: 10
  delay: 5
  changed_when: false

- name: Create SQL mail user (without password)
  postgresql_user:
    name: mail
    state: present
  become: true
  become_user: postgres
  when: (mailservers|length == 0)

- name: Create SQL mail user (with password)
  postgresql_user:
    name: mail
    password: "{{ ispmail_mailserver_password }}"
    state: present
  become: true
  become_user: postgres
  when: (mailservers|length > 0)

- name: Create mailserver SQL database
  postgresql_db:
    name: mailserver
    encoding: UTF-8
    lc_collate: C
    lc_ctype: C
    template: template0
    owner: mail
  become: true
  become_user: postgres
  notify: initialize database

- name: Create SQL pgadmin user
  postgresql_user:
    name: pgadmin
    password: "{{ ispmail_pgadmin_password }}"
    state: present
    db: mailserver
    priv: ALL
  become: true
  become_user: postgres

- name: Create the postgres user map
  blockinfile:
    dest: /etc/postgresql/9.6/main/pg_ident.conf
    marker: "### {mark} ANSIBLE MANAGED BLOCK : MAILMAP ###"
    insertafter: "^#\\s-+"
    content: |
      mailmap         dovecot                 mail
      mailmap         postfix                 mail
      mailmap         root                    mail
      mailmap         postgres                postgres
  notify: restart postgresql

- name: Create postgresql configuration files
  template:
    dest: "/etc/postgresql/9.6/main/{{ item }}"
    src: "{{ item }}.j2"
    mode: 0640
    owner: postgres
    group: postgres
  loop:
    - pg_hba.conf
    - postgresql.conf
  notify: restart postgresql
