---
- name: Install postgres packages
  apt:
    name:
      - sqlite3
    state: present
  register: apt_result
  until: apt_result is succeeded
  retries: 3

- name: Create db file and set ownership
  copy:
    content: ""
    dest: /etc/maildb.sqlite3
    force: false
    owner: root
    group: root
    mode: "0744"
  notify: initialize database
