---
# Requires Ansible >= 1.9
- hosts: mailserver
  roles:
  #- dumpvars
  - ispmail-packages
  - ispmail-certificate
  - ispmail-database
  - ispmail-postfix
  - ispmail-dovecot
  become: yes
  become_user: root
