---
- name: Install packages
  apt:
    name:
      - dnsmasq
      - net-tools
    state: present
    cache_valid_time: 3600

- name: Save original resolv.conf
  copy:
    src: /etc/resolv.conf
    dest: /etc/real-resolvers.conf
    force: false
    remote_src: true

- name: Copy custom resolv.conf
  copy:
    src: resolv.conf
    dest: /etc/resolv.conf

- name: Copy dnsmasq conf
  template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
  notify: restart dnsmasq

- name: Copy dnsmasq hosts
  template:
    src: dnsmasq.hosts.j2
    dest: /etc/dnsmasq.hosts
  notify: restart dnsmasq
