---
- name: Install nginx package
  apt:
    name: nginx
    state: present
    update_cache: true
    cache_valid_time: 3600
  register: apt_result
  until: apt_result is succeeded
  retries: 3
  become: true

- name: Deploy nginx default template for LE challenge
  template:
    src: default.conf.j2
    dest: /etc/nginx/conf.d/default.conf
  become: true
  notify: reload nginx
