---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: molecule/yamllint.yml
platforms:
  # to define DNS server please use only ns. The other ones are overloaded
  # for testing purposes in the create.yml
  - name: north
    groups:
      - mta
      - mda
      - db
      - test
    image: minimum2scp/systemd-stretch
    privileged: true
    command: /sbin/init
    networks:
      - name: external

  - name: south
    groups:
      - mta
      - mda
      - test
    image: minimum2scp/systemd-stretch
    privileged: true
    command: /sbin/init
    networks:
      - name: external

  - name: ns
    image: hugoshaka/dnsmasq-ansible-mailserver
    privileged: true
    command: --conf-file=/etc/dnsmasq.conf
    networks:
      - name: external

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../roles
  inventory:
    links:
      group_vars: ../../group_vars/double
      host_vars: ../../host_vars/test-double
  playbooks:
    create: ../create.yml
    converge: ../playbook.yml
    prepare: ../prepare.yml
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  directory: ../../test/suite/
  additional_files_or_dirs:
    - ../../test/suite/additional/replication.py
  options:
    junit-xml: junit-report.xml
    host: north,south
    maxfail: 2
  lint:
    name: flake8
    options:
      max-line-length: 88
...
