---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: molecule/yamllint.yml
platforms:
  - name: north
    groups:
      - mta
      - mda
      - db
    image: minimum2scp/systemd-stretch
    privileged: true
    command: /sbin/init
    networks:
      - name: external

  - name: south
    groups:
      - mta
      - mda
    image: minimum2scp/systemd-stretch
    privileged: true
    command: /sbin/init
    networks:
      - name: external

  - name: ns
    image: hugoshaka/dnsmasq-asnible-mailserver
    privileged: true
    command: --conf-file=/etc/dnsmasq.conf
    networks:
      - name: external

  - name: client
    image: minimum2scp/systemd-stretch
    privileged: true
    command: /sbin/init
    networks:
      - name: external

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../roles
  inventory:
    links:
      group_vars: ../../group_vars
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
...
