---
- name: Deploy database
  hosts: db
  roles:
    - ispmail-database
  tags:
    - postgres
    - db
  tasks:
    - name: Copy fixtures file
      copy:
        src: fixtures/mailserverdb.sql
        dest: /tmp

    - name: Import fixtures
      postgresql_db:
        name: mailserver
        state: restore
        target: /tmp/mailserverdb.sql
      become: true
      become_user: postgres

    - name: Restart postgres
      service:
        name: postgresql
        state: restarted

- name: Deploy mail transfer agent
  hosts: mta
  roles:
    - ispmail-certificate
    - ispmail-postfix
  tags:
    - postfix
    - mta

- name: Deploy mail delivery agent
  hosts: mda
  roles:
    - ispmail-certificate
    - ispmail-dovecot
  vars:
    ispmail_debug: true
  tags:
    - dovecot
    - mda

# - name: Deploy name server
#   hosts: ns
#   roles:
#     - mailtester-dnsmasq
#   tags:
#     - dnsmasq
...
