---
- name: install required binary packages
  apt: name={{item}} state=installed update_cache=yes
  with_items:
  - postgresql
  - postfix
  - postfix-pgsql
  - swaks
  - dovecot-pgsql
  - dovecot-pop3d
  - dovecot-imapd
  - dovecot-lmtpd
  - dovecot-managesieved
  - spamass-milter
  - spamassassin
  - pwgen

- name: purge Exim installation
  apt: name={{item}} state=absent purge=yes
  with_items:
  - exim4
  - exim4-base
  - exim4-config
  - exim4-daemon-light

- name: make sure postgresql server is started
  service: name=postgresql enabled=yes state=started


