---
- name: Create TLS directories
  file:
    state: directory
    path: "{{ item }}"
    owner: root
    group: root
    mode: 0770
  loop:
    - "{{ node_ca_key | dirname }}"
    - "{{ node_ca_cert | dirname }}"

- name: Generate an OpenSSL private key.
  openssl_privatekey:
    path: "{{ node_ca_key }}"

- name: Generate an OpenSSL CSR.
  openssl_csr:
    path: "{{ node_ca_key }}.csr"
    privatekey_path: "{{ node_ca_key }}"
    common_name: "{{ domain_name }}"

- name: Generate a Self Signed OpenSSL certificate
  # cert is valid for 10 years
  openssl_certificate:
    path: "{{ node_ca_cert }}"
    privatekey_path: "{{ node_ca_key }}"
    csr_path: "{{ node_ca_key }}.csr"
    provider: selfsigned

- name: Recover certificate
  slurp:
    src: "{{ node_ca_cert }}"
  register: certificate

- name: Trust CA on every server
  copy:
    content: "{{ certificate['content'] | b64decode }}"
    dest: "/usr/local/share/ca-certificates/{{ domain_name }}.crt"
    owner: root
    group: root
  delegate_to: "{{ item }}"
  with_inventory_hostnames:
    - mail
  notify: update ca-certificates
