---
- name: Generate an OpenSSL private key
  openssl_privatekey:
    path: "{{ ispmail_public_certificate_keyfile }}"
    state: present
    mode: 0640
    group: root
    owner: root

- name: Generate an OpenSSL Certificate Signing Request
  openssl_csr:
    path: "{{ ispmail_public_certificate_signing_request }}"
    privatekey_path: "{{ ispmail_public_certificate_keyfile }}"
    common_name: "{{ ispmail_public_certificate_domains | join(',') }}"
    country_name: "{{ ispmail_public_certificate_country }}"
    state_or_province_name: "{{ ispmail_public_certificate_state }}"
    locality_name: "{{ ispmail_public_certificate_city }}"
    organization_name: "{{ ispmail_public_certificate_organisation }}"
    organizational_unit_name: "{{ ispmail_public_certificate_orgunit }}"
    email_address: "{{ ispmail_public_certificate_email }}"
    digest: sha512
    state: present

- name: Generate a Self Signed OpenSSL certificate
  openssl_certificate:
    path: "{{ ispmail_public_certificate_location }}"
    privatekey_path: "{{ ispmail_public_certificate_keyfile }}"
    csr_path: "{{ ispmail_public_certificate_signing_request }}"
    valid_in: "{{ ispmail_public_certificate_days_valid * 86400 }}"
    provider: selfsigned
    selfsigned_digest: sha512
    state: present
